---
operation_gw: "192.168.198.2"
internal_gw: "192.168.58.2"
external_gw: "102.168.11.1"

network_ethernet:
    - {conn_name: 'ens33', ip4: "{{ operation_ip }}", gw4: "{{ operation_gw }}"}
    - {conn_name: 'ens34', ip4: "{{ internal_ip }}", gw4: "{{ internal_gw }}"}

#netowrk_bond:
#    - {conn_name: 'bond0', ip4: "{{ external_ip }}", gw4: "{{ external_gw }}"}

#network_bond_slave:
#    - {conn_name: 'ens224', master: 'bond0'}
#    - {conn_name: 'ens256', master: 'bond0'}
