---
##(1)ホスト名の設定
- name: main / Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

##(2)NetworkManagerのリゾルバ設定
- name: main / Set resolver setting
  ini_file:
    dest: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none

##(3)ネームサービススイッチの設定
- name: main / Deploy nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644

##(4)resolv.confの設定
- name: main / Deploy relolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

##(5)hostsファイルの設定
- name: main / Deploy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
